after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --clean --deployment --jobs=$(nproc) --without development production
cache: bundler
dist: trusty
jdk:
  - openjdk7
language: ruby

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.6
    - rvm: 2.5.5
    - rvm: 2.6.2
    - rvm: jruby-9.1.8.0
    - rvm: jruby-9.2.7.0
    - rvm: rbx-3
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-9.1.8.0
    - rvm: jruby-9.2.7.0
