after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --clean --deployment --jobs=$(nproc) --without development production
cache: bundler
dist: trusty
jdk:
  - openjdk7
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
  - jruby-9.1.15.0
  - jruby-9.2.7.0
  - rbx-3
matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-9.2.7.0
