after_success:
  - bundle exec codeclimate-test-reporter
bundler_args: --clean --deployment --jobs=$(nproc) --without development production
cache: bundler
dist: trusty
jdk:
  - openjdk7
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.1.8.0
  - rbx-3
sudo: required
matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-9.1.8.0
